name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release
        uses: BigWigsMods/packager@v1

      - name: Package and release for Burning Crusade Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g classic -w 0

      - name: Package and release for Burning Crusade Classic
        uses: BigWigsMods/packager@v1
        with:
          args: -g bcc -w 0
